### ISSUE TITLE
Cannot turn off dynamic island

### ISSUE THREAD

**Issue by Zyanoo** [Lrdsnow/SimpleKFD#3]
I'm using iphone 13, ios 16.5
After enabled the toggle "Enable dynamic island", applied tweak and respring. My iphone show the dynamic island.
But when opened SimpleKFD to turn it off, the toggle was at off state while the dynamic island still there. So I can't not revert back, try couple of time to on and off the toggle switch and apply but never work.
Tried to change the custom resolution to iphone 13 default, but still not work.

**Comment by augustobob** [comment]
I did used misaka to revert back dynamic island, and custom resolution didn't work at all

**Comment by mxndshock** [comment]
> I did used misaka to revert back dynamic island, and custom resolution didn't work at all

how did you do that? can you pls explain? i can't remove it using misaka

**Comment by augustobob** [comment]
> 

Search the package Gestureify in misaka, once installed enter the advanced options from the package and choose a layout that fits your device, return and apply.

**Comment by mxndshock** [comment]
> Search the package Gestureify in misaka, once installed enter the advanced options from the package and choose a layout that fits your device, return and apply.

Thank you!! It worked

**Comment by Lrdsnow** [comment]
> I did used misaka to revert back dynamic island, and custom resolution didn't work at all

Custom resolution works well on 16.4.1+ (from my tests)

Also dynamic island can now be reverted in app on the latest version with Revert SubType
