### ISSUE TITLE
iPhone 12 Pro, 16.6b1 not applying tweaks

### ISSUE THREAD

**Issue by KernelFox0** [Lrdsnow/SimpleKFD#7]
After I press "Apply Tweaks & Respring", the app freezes for 10 seconds then the phone actually resprings, but no changes are applied.

If I open the app again all toggles are off.

I am trying to apply the custom cc icons tweak

Edit: If I use the hide home bar tweak it respring immediately but the home bar is still there

Edit 2: Changing the subtype works

**Comment by Lrdsnow** [comment]
> If I open the app again all toggles are off.
Its supposed to

The custom cc icons takes quite a few tries to get working
